### ISSUE TITLE
New sequence for : CFO-SWIM off nadir data

### ISSUE THREAD

**Issue by antoinemerle** [wmo-im/BUFR4#214]
### Initial request

In the scope of the CFO Satellite : for the SWIM instruments : 

we have been requested by METEO-FRANCE to generate BUFR data for the `off-nadir` part of the data.

This data needs to be disseminated through EUMETSAT to the member state.

At the moment the data is already implemented locally in EUM and with local code table. 

###  context

![image](https://github.com/user-attachments/assets/41b7ea8c-be1b-4963-8e2c-63d121cb5798)

Presentation attached : 
[SWIM data fot meteo france Off nadir data presentation to WMO.pdf](https://github.com/user-attachments/files/18010556/SWIM.data.fot.meteo.france.Off.nadir.data.presentation.to.WMO.pdf)

# New Table B entries

first a more friendy way to visualise the sequence : 
```yaml
 - code: 001007
   description: satelliteIdentifier
 - code: 001031
  description: centre
 - code: 002019
  description: satelliteInstruments
 - code: 002020,
   description: satelliteClassification
- n_times : delayed replication
  value : 32
  table:
    - code: "005074"
      description: Index in range direction
    - code: "006029"
      description: Wave number
- n_times : fixed replication
  value : 24
  table:
    - code: "005075"
      description: Index in azimuthal direction
    - code: "025082"
      description: Azimuth angle
- code: "005092"
  description: Side track index or along lateral track row number
- code: "001124"
  description: Grid point identifier
- code: "005001"
  description: Latitude
- code: "006001"
  description: Longitude
- code: "004001"
  description: Year
- code: "004002"
  description: Month
- code: "004003"
  description: Day
- code: "004004"
  description: Hour
- code: "004005"
  description: Minute
- code: "004006"
  description: Second
- n_times : delayed Replication
  value : 32
    - code: "005074"
      description: Index in range direction
    - n_times : fixed replication
      value : 24
      table:
        - code: "005075"
          description: Index in azimuthal direction
        - code: "008085"
          description: Beam identifier
        - code: "022161"
          description: Wave spectra
        - code: "008085"
          description: Beam identifier
        - n_times : dealyed replication
          value : 32
          table:
            - code: "002134"
              description: Antenna beam azimuth
            - code: "022161"
              description: Wave spectra

```

Add the following entry to BUFR Table B:

Code | Element name | Units | Scale | Reference value | Data width
-- | -- | -- | -- | -- | --
0 05 092| Side Track Index | Numeric | 0 | -1 | 3

# New entries in existing code and flag tables

## Code Table 0-08-085: Beam identifier

to view current table : https://vocabulary-manager.eumetsat.int/vocabularies/BUFR/WMO/41/TABLE_CODE_FLAG/008085

Action | Value | Meaning
-- | -- | --
Add | 3 | Combined average

# New Table D entries

Add the following sequence `302065` "SWIM off-nadir data":

Table references | Element name | Note
-- | -- | --
301129 | Observing satellite and instruments
1 04 000 | Delayed replication of 4 descriptors | Repeated 32 times (currently), could be 40 for next IPF7
0 31 002 | Extended Delayed descriptor replication factor | Variable: `/nk`
0 05 074 | Index in range direction | Variable: `/nk`, Function: `get_array_range_in_array(netCDF_keys)`
2 02 133 | Change scale from 1 to 6 | Add 5 bits
006029 | Wave number | Variable: `/k_spectra`, Function: `to_subarrays(netCDF_keys)`<br>Wave number vector in m⁻¹<br>Unit: m⁻¹<br>Min: 0.0<br>Max: 1.0<br>Precision: 0.000001
2 02 000 | Cancel change of scale |
1 02 024 | Replication of 2 descriptors | Repeated 24 times
005075 | Index in azimuthal direction | Variable: `/n_phi`, Function: `get_array_range_in_array(netCDF_keys)`<br>Number of `n_phi` vector
025082 | Azimuth angle | Variable: `/phi_vector`, Function: `to_subarrays(netCDF_keys)`<br>`phi_vector(n_phi)`: Phi vector (center of azimuthal bin)<br>Unit: degrees<br>Min: 0.0<br>Max: 180.0<br>Precision: 0.1
2 01 120 | Change width from 11 to 3 |
0 05 037 | Side Track Index | Variable: `/n_posneg`, Function: `apply_data_repetition([-1,1], False, netCDF_keys, None, False)`<br>Default value: `python:[-1,1]*netCDF_keys`<br>0 means -1<br>1 means +1
2 01 000 | Cancel change of width |
0 01 124 | Grid point identifier | Variable: `/n_box`, Function: `apply_data_repetition(netCDF_keys, True, None, 2, False)`<br>1 to 528 for box number but can be higher or lower
0 05 001 | Latitude | Variable: `/lat_spec_l2`, Function: `get_reshaped_data(netCDF_keys, [a,b], [b*a])`<br>Unit: degrees_north<br>Min: -90.0<br>Max: 90.0<br>Precision: 0.001
0 06 001 | Longitude (high accuracy) | Variable: `/lon_spec_l2`, Function: `get_reshaped_data(netCDF_keys, [a,b], [b*a])`<br>Unit: degrees_east<br>Min: -180.0<br>Max: 180.0<br>Precision: 0.001
301130 | High precision timestamp | Variable: `/time_spec_l2`<br>Functions:<br>`get_year_swim(netCDF_keys)`<br>`get_month_swim(netCDF_keys)`<br>`get_day_swim(netCDF_keys)`<br>`get_hour_swim(netCDF_keys)`<br>`get_minute_swim(netCDF_keys)`<br>`get_second_swim(netCDF_keys)`<br>Ntim is the dimension of the time variable; it is equal to 2 because time is given as a pair: seconds and microseconds.<br>Mean time of 2D spectrum area for each `n_tim`<br>Unit: seconds since 2009-01-01 00:00:00<br>Min: 0<br>Max: 662,688,000<br>Precision: 1
1 10 000 | Delayed replication of 10 descriptors | Repeated 32 times (currently), could be 40 for next IPF7
0 31 002 | Extended Delayed Replication Factor |
005074 | Index in range direction | Variable: `/nk`
1 08 024 | Replication of 8 descriptors | Repeated 24 times
005075 | Index in azimuthal direction | Variable: `n_phi`, Function: `get_array_range_in_array(netCDF_keys)`<br>Number of `n_phi` vector
008085 | Beam identifier | Default value: 3<br>Note: Added entry for "Combined average" => 3
022161 | Wave spectra | Variable: `f_2D_combined`, Function: `get_reshaped_data(netCDF_keys, [a,b,c,d,e], [a*b, c*d]))`<br>For 2D mean height spectrum combining all spectral beams without ambiguity removal<br>`f_2D_combined(nk, n_phi, n_posneg, n_box)`<br>Unit: m⁴<br>Min: 0.0<br>Max: 1000.0<br>Precision: 0.0001
008085 | Beam identifier | Default value: 7<br>Note: Set to missing (7)
1 02 000 | Delayed replication of 2 descriptors |
0 31 002 | Extended delayed descriptor replication factor | Variable: `/n_beam_l2`, Default value: 3<br>Dimension of `n_beam_l2`: expected to be 1, but currently is 3
0 02 134 | Antenna beam azimuth | Variable: `/n_beam_l2`, Function: `get_antenna_beam_per_n_beam(netCDF_keys)`<br>`N_beam_l2` defines the number of spectrum beams used to construct a wave spectrum.<br>- Current configuration: beams at 6°, 8°, and 10°, so `N_beam_l2` = 3.<br>- Future configuration may use only 10°, so `n_beam_l2` = 1.<br>If `n_beam` is 1, value will be 10.<br>If `n_beam` is 3, values will be 6, 8, and 10.
022161 | Wave spectra | Variable: `f2_D`, Function: `get_reshaped_data(netCDF_keys, [a,b,c,d,e], [a*b*e, c*d])`<br>For 2D height spectrum for each spectral beam without ambiguity removal<br>`f2_D(nk, n_phi, n_posneg, n_box, n_beam_l2)`<br>Unit: m⁴<br>Min: 0.0<br>Max: 1000.0<br>Precision: 0.0001

where ``

### Requestor(s)

lotfi.aouf@meteo.fr
AOUF LOTFI (Scientifique)
Département Marine et Océanographie / R&D
Météo-France - DirOP/MAR/RD

### Stakeholder(s)

EUMETSAT - MMDS
EUMETSAT - THOMAS Heinemann

### Publication(s)

Impact on 
table B : 1 new entry
Flag/code table : update existing entry
Table D : one new entry

### Expected impact of change

None

### Collaborators

Simon Elliott
Thomas Heinemann

### Validation

 > **disclaimer : YOU NEED TO HAVE ECCODES `3.39` TO DECODE DATA (or a SW allowing nested replication)**

[REGRESS-SWIM-OGDR(2).zip](https://github.com/user-attachments/files/18407106/REGRESS-SWIM-OGDR.2.zip)

table local element from eccodes

```
005092|SideTrackIndexOrAlongLateralTrackRowNumber|Numeric|SideTrackIndexOrAlongLateralTrackRowNumber|Numeric|0|-1|3|Numeric|0|1
```
```
